values:
- Basic
- Item
- Pok√©mon Tool
- Stage 1
- Stage 2
- Supporter
human_readable_values: []
has_more_values: false
hash_key: null
serdes/meta:
- model: Database
  id: postgres-local
- model: Schema
  id: uploads
- model: Table
  id: temporal_forces_diff_20240509161738
- model: Field
  id: subtype1
- model: FieldValues
  id: '0'
created_at: '2024-05-09T16:17:42.019611Z'
last_used_at: '2024-05-09T16:17:42.019611Z'
type: full
