values:
- ACE SPEC
- Ancient
- Eternamax
- ex
- EX
- ex-3
- Fusion Strike
- Future
- GX
- Item
- Pok√©mon Tool
- Prime
- Prism Star
- Radiant
- Rapid Strike
- Single Strike
- SP
- Special
- Star
- Supporter
- TAG TEAM
- Team Plasma
- Tera
- Ultra Beast
- V
- null
human_readable_values: []
has_more_values: false
hash_key: null
serdes/meta:
- model: Database
  id: postgres-local
- model: Schema
  id: pokemon
- model: Table
  id: pokemon_cards
- model: Field
  id: subtype2
- model: FieldValues
  id: '0'
created_at: '2023-08-21T20:32:19.860786Z'
last_used_at: '2025-02-28T15:06:27.502874Z'
type: full
