values:
- ðŸ’©
- do
- handle
- Know
- -Ï€
human_readable_values: []
has_more_values: false
hash_key: null
serdes/meta:
- model: Database
  id: postgres-local
- model: Schema
  id: uploads
- model: Table
  id: super_long_name_of_a_spreadsheet_xlsx_lxs_final__20240108151105__mbarchiv__1755547320
- model: Field
  id: column_3
- model: FieldValues
  id: '0'
created_at: '2024-01-08T15:11:05.711543Z'
last_used_at: '2024-01-08T15:11:05.711543Z'
type: full
