values:
- 10 Barrel Brewing Company
- 18th Street Brewery
- 21st Amendment Brewery
- 2 Towns Ciderhouse
- 3 Daughters Brewing
- 450 North Brewing Company
- 4 Hands Brewing Company
- 7 Seas Brewing Company
- 7venth Sun
- Abita Brewing Company
- AC Golden Brewing Company
- Against the Grain Brewery
- Against The Grain Brewery
- Airways Brewing Company
- Alameda Brewing
- Alaskan Brewing Company
- Ale Asylum
- Alltech's Lexington Brewing Company
- Amnesia Brewing Company
- Anchor Brewing Company
- Anderson Valley Brewing Company
- Angry Minnow
- Angry Minnow Brewing Company
- Angry Orchard Cider Company
- Anthem Brewing Company
- Appalachian Mountain Brewery
- Arcadia Brewing Company
- Arctic Craft Brewery
- Armadillo Ale Works
- Armstrong Brewing Company
- Asher Brewing Company
- Asheville Brewing Company
- Aslan Brewing Company
- Aspen Brewing Company
- Astoria Brewing Company
- Atwater Brewery
- Austin Beerworks
- Avery Brewing Company
- Aviator Brewing Company
- Back East Brewing Company
- Back Forty Beer Company
- Bale Breaker Brewing Company
- Ballast Point Brewing Company
- Banner Beer Company
- Bare Hands Brewery
- Barrio Brewing Company
- Base Camp Brewing Co.
- Bauhaus Brew Labs
- Baxter Brewing Company
- Beach Brewing Company
- Beer Works Brewery
- Bell's Brewery
- Bent Brewstillery
- Bent Paddle Brewing Company
- Berkshire Brewing Company
- Big Bend Brewing Company
- Big Choice Brewing
- Big Elm Brewing
- Big Lake Brewing
- Big Muddy Brewing
- Big River Brewing Company
- Big Sky Brewing Company
- Big Storm Brewing Company
- Big Wood Brewery
- Birdsong Brewing Company
- Bitter Root Brewing
- Black Acre Brewing Co.
- Black Market Brewing Company
- Blackrocks Brewery
- Black Shirt Brewing Company
- Black Tooth Brewing Company
- Blue Blood Brewing Company
- Blue Dog Mead
- Blue Hills Brewery
- Blue Mountain Brewery
- Blue Owl Brewing
- Blue Point Brewing Company
- Bohemian Brewery
- Bold City Brewery
- Bolero Snort Brewery
- Bomb Beer Company
- Bonfire Brewing Company
- Borderlands Brewing Company
- Boston Beer Company
- Boulder Beer Company
- Boulevard Brewing Company
- Boxcar Brewing Company
- Bozeman Brewing Company
- Branchline Brewing Company
- Breakside Brewery
- Breckenridge Brewery
- Brew Bus Brewing
- Brewery Terra Firma
- Brewery Vivant
- Brew Link Brewing
- Brindle Dog Brewing Company
- Broad Brook Brewing LLC
- Broken Tooth Brewing Company
- Brooklyn Brewery
- Buckbean Brewing Company
- Buckeye Brewing
- BuckleDown Brewing
- Buffalo Bayou Brewing Company
- Burn 'Em Brewing
- Burnside Brewing Co.
- Butcher's Brewing
- Butternuts Beer and Ale
- Caldera Brewing Company
- Cambridge Brewing Company
- Cans Bar and Canteen
- Cape Ann Brewing Company
- Cape Cod Beer
- Capital Brewery
- Carolina Beer & Beverage
- Carolina Brewery
- Carton Brewing Company
- Cascadia Ciderworks United
- Catawba Brewing Company
- Catawba Island Brewing
- Catawba Valley Brewing Company
- Cedar Creek Brewery
- Centennial Beer Company
- Center of the Universe Brewing C...
- Central Coast Brewing Company
- Champion Brewing Company
- Chapman's Brewing
- Chatham Brewing
- Cheboygan Brewing Company
- Christian Moerlein Brewing Company
- Churchkey Can Company
- Ciderboys
- Cigar City Brewing Company
- Cisco Brewers
- Claremont Craft Ales
- Coalition Brewing Company
- Coastal Empire Beer Company
- Coastal Extreme Brewing Company
- COAST Brewing Company
- College Street Brewhouse and Pub
- Confluence Brewing Company
- COOP Ale Works
- Core Brewing & Distilling Company
- Cottrell Brewing
- Covington Brewhouse
- Crabtree Brewing Company
- Crazy Mountain Brewing Company
- Creature Comforts
- Crooked Fence Brewing Company
- Crow Peak Brewing Company
- Crystal Springs Brewing Company
- Cutters Brewing Company
- Dad & Dude's Breweria
- Daredevil Brewing Company
- Dave's Brewfarm
- David's Ale Works
- DC Brau Brewing Company
- Dead Armadillo Craft Brewing
- Deep Ellum Brewing Company
- Defiance Brewing Company
- Denali Brewing Company
- Denver Beer Company
- Deschutes Brewery
- Destihl Brewery
- Devil's Backbone Brewing Company
- Devil's Canyon Brewery
- Dick's Brewing Company
- Dirty Bucket Brewing Company
- D.L. Geary Brewing Company
- Dock Street Brewery
- Dolores River Brewery
- Downeast Cider House
- Dry Dock Brewing Company
- Due South Brewing Company
- Dundee Brewing Company
- Eddyline Brewery & Restaurant
- Elevator Brewing Company
- Emerald City Beer Company
- Engine 15 Brewing
- Engine House 9
- Epic Brewing
- Everybody's Brewing
- Evil Czech Brewery
- Evil Twin Brewing
- Fargo Brewing Company
- Fate Brewing Company
- Fat Head's Brewery
- Fearless Brewing Company
- Fiddlehead Brewing Company
- Figueroa Mountain Brewing Company
- Finch's Beer Company
- Firestone Walker Brewing Company
- Flat 12 Bierwerks
- Flat Rock Brewing Company
- Flesk Brewing Company
- Flying Dog Brewery
- Flying Mouse Brewery
- Foolproof Brewing Company
- Forgotten Boardwalk
- Fort George Brewery
- Fort Pitt Brewing Company
- Fort Point Beer Company
- Founders Brewing Company
- Four Corners Brewing Company
- 'Four Fathers Brewing '
- Four Horsemen Brewing Company
- Four Peaks Brewing Company
- Four String Brewing Company
- Frankenmuth Brewery
- Freetail Brewing Company
- Fremont Brewing Company
- French Broad Brewery
- Frog Level Brewing Company
- Fullsteam Brewery
- Geneva Lake Brewing Company
- Glabrous Brewing Company
- Golden Road Brewing
- Gonzo's BiggDogg Brewing
- Goodlife Brewing Co.
- Good Life Brewing Company
- Good People Brewing Company
- Goose Island Brewery Company
- Goose Island Brewing Company
- Gore Range Brewery
- Grand Canyon Brewing Company
- Grapevine Craft Brewery
- Great Crescent Brewery
- Great Divide Brewing Company
- Great Northern Brewing Company
- Great Raft Brewing Company
- Great River Brewery
- Greenbrier Valley Brewing Company
- Green Room Brewing
- Grey Sail Brewing Company
- Grey Sail Brewing of Rhode Island
- Griffin Claw Brewing Company
- Grimm Brothers Brewhouse
- Hale's Ales
- Half Acre Beer Company
- Half Full Brewery
- Hangar 24 Craft Brewery
- Hardywood Park Craft Brewery
- Harpoon Brewery
- Harvest Moon Brewing Company
- Hawai'i Nui Brewing Co.
- Headlands Brewing Company
- Heavy Seas Beer
- Hess Brewing Company
- High Hops Brewery
- High Noon Saloon And Brewery
- Hilliard's Beer
- Hinterland Brewery
- Hop Farm Brewing Company
- Hops & Grain Brewery
- Hops & Grains Brewing Company
- Hop Valley Brewing Company
- Hopworks Urban Brewery
- Horny Goat Brew Pub
- Howard Brewing Company
- Indeed Brewing Company
- Independence Brewing Company
- Indiana City Brewing
- Infamous Brewing Company
- Intuition Ale Works
- Ipswich Ale Brewery
- Iron Hill Brewery & Restaurant
- Jackalope Brewing Company
- Jackie O's Pub & Brewery
- Jack's Abby Craft Lagers
- Jack's Hard Cider (Hauser Estate...
- Jailbreak Brewing Company
- James Page Brewing Company
- Joseph James Brewing Company
- Kalona Brewing Company
- Karbach Brewing Company
- KelSo Beer Company
- Kenai River Brewing Company
- Kettle House Brewing Company
- Keweenaw Brewing Company
- King Street Brewing Company
- Kirkwood Station Brewing Company
- Kona Brewing Company
- Krebs Brewing Company (Pete's Pl...
- Kulshan Brewery
- La Cumbre Brewing Company
- Lancaster Brewing Company
- Latitude 42 Brewing Company
- Laughing Dog Brewing Company
- Lavery Brewing Company
- Lazy Monk Brewing
- Lewis and Clark Brewing Company
- Lift Bridge Brewing Company
- Liquid Hero Brewery
- Lonerider Brewing Company
- Lone Tree Brewing Company
- Long Trail Brewing Company
- Lost Nation Brewing
- Lost Rhino Brewing Company
- Lucette Brewing Company
- Lucky Town Brewing Company
- Lumberyard Brewing Company
- Macon Beer Company
- MacTarnahans Brewing Company
- Madtree Brewing Company
- Magic Hat Brewing Company
- Mammoth Brewing Company
- Manayunk Brewing Company
- Manzanita Brewing Company
- Marble Brewery
- Marshall Wharf Brewing Company
- Martin House Brewing Company
- Matt Brewing Company
- Maui Brewing Company
- Mavericks Beer Company
- Meckley's Cidery
- Mehana Brewing Co.
- Miami Brewing Company
- Mickey Finn's Brewery
- Midnight Sun Brewing Company
- Mike Hess Brewing Company
- Mikerphone Brewing
- Mikkeller
- MillKing It Productions
- Milwaukee Brewing Company
- Minhas Craft Brewery
- Mission Brewery
- Moab Brewery
- Moat Mountain Smoke House & Brew...
- Modern Monks Brewery
- Modern Times Beer
- Mogollon Brewing Company
- Monkey Paw Pub & Brewery
- Montauk Brewing Company
- Morgan Street Brewery
- Mother Earth Brew Company
- Mother Earth Brewing Company
- Mother's Brewing
- 'Mountain Town Brewing Company '
- Mudshark Brewing Company
- Mustang Brewing Company
- Narragansett Brewing Company
- Natian Brewery
- Nebraska Brewing Company
- Neshaminy Creek Brewing Company
- New Belgium Brewing Company
- Newburgh Brewing Company
- Newburyport Brewing Company
- New England Brewing Company
- New Orleans Lager & Ale Brewing ...
- New Republic Brewing Company
- New South Brewing Company
- Night Shift Brewing
- NoDa Brewing Company
- Northampton Brewery
- North Country Brewing Company
- 'NorthGate Brewing '
- Northwest Brewing Company
- Northwoods Brewpub
- Notch Brewing Company
- Oakshire Brewing
- Oasis Texas Brewing Company
- Occidental Brewing Company
- Odyssey Beerwerks
- O'Fallon Brewery
- Okoboji Brewing Company
- Old Forge Brewing Company
- Orlison Brewing Company
- Orpheus Brewing
- Oskar Blues Brewery
- Oskar Blues Brewery (North Carol...
- Otter Creek Brewing
- Ozark Beer Company
- Palisade Brewing Company
- Pateros Creek Brewing Company
- Payette Brewing Company
- Peace Tree Brewing Company
- Peak Organic Brewing Company
- Pedernales Brewing Company
- People's Brewing Company
- Perrin Brewing Company
- Pete's Brewing Company
- Petoskey Brewing
- Phoenix Ale Brewery
- Pikes Peak Brewing Company
- Pine Street Brewery
- Piney River Brewing Company
- Pipeworks Brewing Company
- Pisgah Brewing Company
- Pizza Port Brewing Company
- Platform Beer Company
- Pollyanna Brewing Company
- Portside Brewery
- Prescott Brewing Company
- Pug Ryan's Brewery
- Pyramid Breweries
- Quest Brewing Company
- Rahr & Sons Brewing Company
- Real Ale Brewing Company
- Red Hare Brewing Company
- Redhook Brewery
- Red Shedman Farm Brewery and Hop...
- Redstone Meadery
- Red Tank Cider Company
- Refuge Brewery
- Renegade Brewing Company
- Revolution Brewing
- Revolution Brewing Company
- Rhinegeist Brewery
- Right Brain Brewery
- Rising Tide Brewing Company
- River North Brewery
- Rivertown Brewing Company
- Rivertowne Brewing Company
- Roanoke Railhouse Brewery
- Rochester Mills Brewing Company
- Rogue Ales
- RoughTail Brewing Company
- Round Guys Brewing
- Ruhstaller Beer Company
- Saint Archer Brewery
- Sanitas Brewing Company
- Santa Cruz Mountain Brewing
- Santa Fe Brewing Company
- SanTan Brewing Company
- Saugatuck Brewing Company
- Schilling & Company
- Schlafly Brewing Company
- Seabright Brewery
- Sea Dog Brewing Company
- Seattle Cider Company
- Seven Brides Brewery
- Seventh Son Brewing Company
- Shebeen Brewing Company
- Sherwood Forest Brewers
- Shipyard Brewing Company
- Sierra Nevada Brewing Company
- Sietsema Orchards and Cider Mill
- Silverton Brewery
- Sixpoint Craft Ales
- Ska Brewing Company
- Slanted Rock Brewing Company
- SlapShot Brewing Company
- Sleeping Lady Brewing Company
- Sly Fox Brewing Company
- Smartmouth Brewing Company
- Snake River Brewing Company
- Sockeye Brewing Company
- Southampton Publick House
- South Austin Brewery
- Southern Oregon Brewing Company
- Southern Prohibition Brewing Com...
- Southern Star Brewing Company
- Speakasy Ales & Lagers
- Spilker Ales
- Spiteful Brewing Company
- Sprecher Brewing Company
- Spring House Brewing Company
- Starr Hill Brewery
- Steamworks Brewing Company
- Stevens Point Brewery
- Stillmank Beer Company
- Stillwater Artisanal Ales
- St. Julian Winery
- Stone Coast Brewing Company
- Straight to Ale
- Straub Brewery
- Summit Brewing Company
- Sunken City Brewing Company
- Sun King Brewing Company
- Surly Brewing Company
- Swamp Head Brewery
- Swashbuckler Brewing Company
- SweetWater Brewing Company
- TailGate Beer
- Tallgrass Brewing Company
- Tamarack Brewing Company
- Tampa Bay Brewing Company
- Tapistry Brewing
- Taxman Brewing Company
- Telluride Brewing Company
- Temperance Beer Company
- Terrapin Brewing Company
- Texian Brewing Co.
- The Alchemist
- The Black Tooth Brewing Company
- The Brewer's Art
- The Bronx Brewery
- The Dudes' Brewing Company
- The Just Beer Project
- The Lion Brewery
- The Manhattan Brewing Company
- The Mitten Brewing Company
- The Right Brain Brewery
- The Traveler Beer Company
- Third Street Brewhouse
- Thomas Hooker Brewing Company
- Three Creeks Brewing
- Three Notch'd Brewing Company
- Three Pints Brewing
- Thunderhead Brewing Company
- Tin Man Brewing Company
- Tin Roof Brewing Company
- Tommyknocker Brewery
- Tonka Beer Company
- Tractor Brewing Company
- Triangle Brewing Company
- Tr√∂egs Brewing Company
- Twin Lakes Brewing Company
- Twisted Pine Brewing Company
- Twisted X Brewing Company
- Two Beers Brewing Company
- Two Brothers Brewing Company
- Two Henrys Brewing Company
- Two Roads Brewing Company
- Uinta Brewing Company
- Ukiah Brewing Company
- Uncle Billy's Brewery and Smokeh...
- Uncle John's Fruit House Winery
- Uncommon Brewers
- Union Craft Brewing
- Upland Brewing Company
- Upslope Brewing Company
- Upstate Brewing Company
- Utah Brewers Cooperative
- Vander Mill Ciders
- Vault Brewing Company
- Voodoo Brewery
- Wachusett Brewing Company
- Warbird Brewing Company
- Warped Wing Brewing Company
- Westbrook Brewing Company
- Westfield River Brewing Company
- Weston Brewing Company
- West Sixth Brewing
- White Birch Brewing
- White Flame Brewing Company
- Widmer Brothers Brewing Company
- Wild Onion Brewing Company
- Wild Wolf Brewing Company
- Wildwood Brewing Company
- Wind River Brewing Company
- Wingman Brewers
- Wisconsin Brewing Company
- Wiseacre Brewing Company
- Witch's Hat Brewing Company
- Wolf Hills Brewing Company
- Wolverine State Brewing Company
- Woodchuck Hard Cider
- Woodstock Inn, Station & Brewery
- Wormtown Brewery
- Worthy Brewing Company
- Wynkoop Brewing Company
human_readable_values: []
has_more_values: false
hash_key: null
serdes/meta:
- model: Database
  id: postgres-local
- model: Schema
  id: uploads
- model: Table
  id: breweries_20230626143543
- model: Field
  id: name
- model: FieldValues
  id: '0'
created_at: '2023-08-21T20:31:57.295373Z'
last_used_at: '2023-08-21T20:31:57.295373Z'
type: full
